import { app, BrowserWindow, Menu, shell } from "electron";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { registerIpc } from "./ipc.js";
import { registerTerminalIpc } from "./terminal.js";

/**
 * Electron main process. It reuses polyclaude's existing Node core directly
 * (vault, switcher, crypto, usage) via the IPC handlers in ipc.ts — no logic is
 * duplicated. The renderer is a Vite React app served from the dev server in
 * development and from dist/renderer in a packaged build.
 */

const dir = path.dirname(fileURLToPath(import.meta.url));
// Set by `npm run gui:dev` so the window loads the Vite dev server (HMR);
// unset for `npm run gui` and packaged builds, which load the built files.
const DEV_URL = process.env.POLY_DEV_SERVER;
// Poly icon (generated by scripts/gen-icon.mjs); dist/main → repo/assets.
const ICON = path.join(dir, "../../assets/icon.png");

function createWindow(): void {
  const win = new BrowserWindow({
    width: 1060,
    height: 740,
    minWidth: 900,
    minHeight: 600,
    backgroundColor: "#16131e",
    show: false,
    icon: ICON,
    autoHideMenuBar: true, // no File/Edit/View/… bar (also removed globally below)
    titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "default",
    webPreferences: {
      preload: path.join(dir, "../preload/index.cjs"),
      contextIsolation: true,
      sandbox: false,
    },
  });

  win.once("ready-to-show", () => win.show());

  // Open external links in the system browser, never in-app.
  win.webContents.setWindowOpenHandler(({ url }) => {
    void shell.openExternal(url);
    return { action: "deny" };
  });

  if (DEV_URL) {
    void win.loadURL(DEV_URL);
  } else {
    void win.loadFile(path.join(dir, "../renderer/index.html"));
  }
}

// The Windows installer (and `polyclaude --install-cli/--uninstall-cli`) drives
// the CLI-shim install headlessly: do the work, then exit without a window.
const cliFlag = process.argv.find((a) => a === "--install-cli" || a === "--uninstall-cli");

app.whenReady().then(async () => {
  if (cliFlag) {
    const { runCliAction } = await import("./cli-install.js");
    const res = await runCliAction(cliFlag === "--install-cli" ? "install" : "uninstall");
    app.exit(res.ok ? 0 : 1);
    return;
  }
  Menu.setApplicationMenu(null); // remove the default File/Edit/View/Window/Help menu
  if (process.platform === "darwin" && app.dock) {
    try {
      app.dock.setIcon(ICON);
    } catch {
      /* dev-only nicety */
    }
  }
  registerIpc();
  registerTerminalIpc();
  createWindow();
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});
